### ISSUE TITLE
Building and running

### ISSUE THREAD

**Issue by karajrish** [jfroom/portfolio-web#1]
Could you please provide me a simple step-by-step guide to running this site on my local machine. Was not able to comprehend the README file.
Thanks

**Comment by jfroom** [comment]
@karajrish Are you familiar with NPM & grunt projects? Links to documentation for those can be found here:  https://github.com/jfroom/portfolio-web#getting-started 

Unfortunately, I'm not too motivated to maintain this repo since it was really just an exploration exercise & tool for my own site which I haven't touched much over the years. In fact, I'm not sure I'd use the same approach entirely if I had it to do over again. 

If you are interested in static site generators, maybe explore some of these projects where there is a richer community? https://www.staticgen.com/

**Comment by karajrish** [comment]
@jfroom Unfortunately not. 
Well, your site's design is very catchy hence I thought I could use your help setting it up.

Nevertheless, thanks for the links!

**Comment by jfroom** [comment]
I've made some minor updates to the [getting started]( https://github.com/jfroom/portfolio-web#getting-started) section. 

However, because there are a variety of different ways to get the pre-requisite dependencies (node, npm, grunt, protractor, image-magic) installed & running on a local or virtual system — I am apprehensive about trying to document that part of the process. There are better resources for that in the links provided. Most repositories have a similar stance — or don't even have a getting started section ([1](https://github.com/jsoverson/grunt-open), [2](https://github.com/jsoverson/grunt-open), [3](https://github.com/sindresorhus/grunt-sass)).
